### ISSUE TITLE
PoolMr: remove currency columns and display currencies next to numbers

### ISSUE THREAD

**Issue by Eddman** [Deutsche-Boerse-Risk/DAVe-UI#24] opened 2017-06-21 08:20 UTC
![image](https://user-images.githubusercontent.com/209500/27374181-35ce38a0-566b-11e7-9ef4-ac37a4aea12f.png)

**Comment by markadir** [comment] 2017-08-01 06:35
If you keep the "Magrin currency" column and write "in Margin currency" you don't need to display currency next to number and can save space. Only add currency code where It's not specified i.e. in over/under collaterization in Clearing ccy.

**Comment by Eddman** [comment] 2017-08-04 09:14
@markadir I agree to keep `Magrin currency` column. But the label `in Margin currency` is longer then `EUR` for instance. Much more we should be consistent with other views.

For me the label `in XYZ currency` makes sense only in case of over/under(?). All other columns are in margin currency right (except `Adjusted Exchange Rate` of course)?

**Comment by markadir** [comment] 2017-08-04 09:24
Yep, I agree. It's just has to be consistent. I was thinking that you can have column names in two rows while EUR has to be right next to the number thus making each column wider.

**Comment by Eddman** [comment] 2017-08-04 11:04
@markadir So the agreement is to add margin currency to all columns, except over/under in clearing curr and to remove the Clearing currency column? Right?

**Comment by Eddman** [comment] 2017-08-18 08:58
@markadir ping :smile:

**Comment by markadir** [comment] 2017-08-18 09:41
Yes, your Analysis of the issue is correct. Thank you!

**Comment by Eddman** [comment] 2017-08-18 11:24
@markadir Please verify and close the issue.

**Comment by markadir** [comment] 2017-08-18 11:27
Implemented and reviewed. Closing Issue.

**Closed by markadir** 2017-08-18 11:27 UTC
Labels: enhancement, P1: High
